
- name: Install AWS CLI v2 on Ubuntu
  hosts: servers
  become: yes

  tasks:
    - name: Install unzip and required tools
      apt:
        name: [unzip, curl]
        state: present
        update_cache: yes

    - name: Download AWS CLI v2 installer
      get_url:
        url: https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip
        dest: /tmp/awscliv2.zip
        mode: '0644'

    - name: Unzip AWS CLI installer
      unarchive:
        src: /tmp/awscliv2.zip
        dest: /tmp
        remote_src: yes

    - name: Install AWS CLI
      command: /tmp/aws/install
      args:
        creates: /usr/local/bin/aws

    - name: Verify AWS CLI installation
      command: aws --version
      register: aws_version
      changed_when: false

    - name: Show installed AWS CLI version
      debug:
        msg: "AWS CLI version installed: {{ aws_version.stdout }}"
